CREATE TABLE dog (
    nameid VARCHAR2(26 Byte), 
    stateid VARCHAR2(10 Byte),
    limeid VARCHAR2(10 Byte)
);

SELECT*
FROM VIOLATIONSPOP

INSERT INTO dog(nameid, stateid, limeid) 
VALUES 
    (32, 'Zelda', 'F')
    (11, 'Annie', 'F'),
    (32, 'Ace', 'M'),
    (32, 'Zelda', 'F'),
    (5, 'Diesel', 'M'),
    (6, 'Tilly', 'F'),
    (7, 'Leroy', 'M'),
    (8, 'Olivia', 'F');

SELECT 
	DISTINCT 
       nameid,
       stateid, limeid
FROM 
	dog
COMMIT

SELECT*
FROM dog
DROP TABLE TESTERPLATE
CREATE TABLE Violations1
AS SELECT*
FROM Violations;

SELECT*
FROM VIOLATIONS3;

DROP TABLE VIOLATIONS2

COMMIT

--CREATING DATABASE --CREATING DATABASE --CREATING DATABASE
--CREATING DATABASE --CREATING DATABASE --CREATING DATABASE
--CREATING DATABASE --CREATING DATABASE --CREATING DATABASE

--TABLE 1 --TABLE 1 --TABLE 1 --TABLE 1 --TABLE 1 --TABLE 1 --TABLE 1 --TABLE 1
--TABLE 1 --TABLE 1 --TABLE 1 --TABLE 1 --TABLE 1 --TABLE 1 --TABLE 1 --TABLE 1

CREATE TABLE Violations1
AS SELECT*
FROM Violations;

ALTER TABLE Violations1
DROP COLUMN summons_number
ALTER TABLE Violations1
DROP COLUMN ISSUE_DATE
ALTER TABLE Violations1
DROP COLUMN Violation_Time
ALTER TABLE Violations1
DROP COLUMN VIOLATION
ALTER TABLE Violations1
DROP COLUMN FINE_AMOUNT
ALTER TABLE Violations1
DROP COLUMN PENALTY_AMOUNT
ALTER TABLE Violations1
DROP COLUMN INTEREST_AMOUNT
ALTER TABLE Violations1
DROP COLUMN REDUCTION_AMOUNT
ALTER TABLE Violations1
DROP COLUMN PAYMENT_AMOUNT
ALTER TABLE Violations1
DROP COLUMN AMOUNT_DUE
ALTER TABLE Violations1
DROP COLUMN PRECINCT
ALTER TABLE Violations1
DROP COLUMN COUNTY
ALTER TABLE Violations1
DROP COLUMN ISSUING_AGENCY
ALTER TABLE Violations1
DROP COLUMN VIOLATION_STATUS
ALTER TABLE Violations1
DROP COLUMN SUMMONS_IMAGE

SELECT*
FROM Vehicle_Info

COMMIT

DROP TABLE Vehicle_Info

CREATE TABLE Vehicle_Info(
    PLATE VARCHAR2(26 Byte), 
    STATE VARCHAR2(10 Byte),
    LICENSE_TYPE VARCHAR2(10 Byte)
);

CREATE TABLE Vehicle_Info(
    PLATE VARCHAR2(26 Byte)Primary Key, 
    STATE VARCHAR2(10 Byte),
    LICENSE_TYPE VARCHAR2(10 Byte)
);

SELECT*
FROM Vehicle_Info;
--COPY DATA INTO Vehicle_Info
INSERT INTO Vehicle_Info( PLATE, STATE, LICENSE_TYPE) 
SELECT
    PLATE,
    STATE,
    LICENSE_TYPE
FROM
    VIOLATIONSPOP
    
ALTER TABLE Vehicle_Info
ADD PRIMARY KEY(PLATE);
--Identify Multiple Plates
SELECT PLATE, COUNT(*)
FROM Vehicle_Info
GROUP BY PLATE
HAVING COUNT(*)>1;

--Delete Duplicate
DELETE T
FROM
(
SELECT *
, DupRank = ROW_NUMBER() OVER (
              PARTITION BY PLATE
              ORDER BY (SELECT NULL)
            )
FROM Vehicle_Info
) AS T
WHERE DupRank > 1 

--Delete
DELETE FROM Vehicle_Info
WHERE PLATE IN(
    SELECT PLATE
    FROM(
        SELECT PLATE,
        ROW_NUMBER() OVER (PARTITION BY STATE, LICENSE_TYPE)AS ROWNUM
        FROM Vehicle_Info
    )AS SUB
WHERE ROWNUM > 1
);

DROP TABLE Vehicle_Info

--TABLE 2 --TABLE 2 --TABLE 2 --TABLE 2 --TABLE 2 --TABLE 2 --TABLE 2 --TABLE 2 
--TABLE 2 --TABLE 2 --TABLE 2 --TABLE 2 --TABLE 2 --TABLE 2 --TABLE 2 --TABLE 2 
--REDACT
--REDACT
--REDACT
--TODO
CREATE TABLE Vehicle_Type(
    PLATE VARCHAR2(26 Byte), 
    LICENSE_TYPE VARCHAR2(10 Byte)
);

INSERT INTO Vehicle_Type(PLATE, LICENSE_TYPE) 
SELECT
    PLATE,
    LICENSE_TYPE
FROM
    VIOLATIONS1
    
SELECT*
FROM Vehicle_Type

DROP TABLE Vehicle_Type

--TABLE 3 --TABLE 3 --TABLE 3 --TABLE 3 --TABLE 3 --TABLE 3 --TABLE 3 --TABLE 3
--TABLE 3 --TABLE 3 --TABLE 3 --TABLE 3 --TABLE 3 --TABLE 3 --TABLE 3 --TABLE 3

CREATE TABLE Summoned_Vehicle_Owner(
    SUMMONS_NUMBER VARCHAR2(36 Byte),
    PLATE VARCHAR2(26 Byte)
);
INSERT INTO Summoned_Vehicle_Owner(SUMMONS_NUMBER, PLATE) 
SELECT
    SUMMONS_NUMBER,
    PLATE
FROM VIOLATIONS

COMMIT

SELECT*
FROM Summoned_Vehicle_Owner
--Alter summons_number to be primary key
ALTER TABLE Summoned_Vehicle_Owner
ADD PRIMARY KEY (SUMMONS_NUMBER);

--TABLE 4 --TABLE 4 --TABLE 4 --TABLE 4 --TABLE 4 --TABLE 4 --TABLE 4 --TABLE 4 
--TABLE 4 --TABLE 4 --TABLE 4 --TABLE 4 --TABLE 4 --TABLE 4 --TABLE 4 --TABLE 4 

CREATE TABLE Summons(
    SUMMONS_NUMBER VARCHAR2(36 Byte),
    ISSUE_DATE DATE,
    VIOLATION_TIME VARCHAR2(26 Byte),
    VIOLATION VARCHAR2(128 Byte),
    ISSUING_AGENCY VARCHAR2(40 Byte),
    VIOLATION_STATUS VARCHAR2(128 Byte)
);

INSERT INTO Summons(SUMMONS_NUMBER,ISSUE_DATE,VIOLATION_TIME,VIOLATION,ISSUING_AGENCY,VIOLATION_STATUS) 
SELECT
    SUMMONS_NUMBER,
    ISSUE_DATE,
    VIOLATION_TIME,
    VIOLATION,
    ISSUING_AGENCY,
    VIOLATION_STATUS
FROM
    VIOLATIONS
    
SELECT*
FROM Summons

ALTER TABLE Summons
ADD PRIMARY KEY (SUMMONS_NUMBER);

DROP TABLE SUMMONS

--TABLE 5 --TABLE 5 --TABLE 5 --TABLE 5 --TABLE 5 --TABLE 5 --TABLE 5 --TABLE 5 
--TABLE 5 --TABLE 5 --TABLE 5 --TABLE 5 --TABLE 5 --TABLE 5 --TABLE 5 --TABLE 5 

CREATE TABLE Fines(
    SUMMONS_NUMBER VARCHAR2(36 Byte),
    PLATE VARCHAR2(26 Byte), 
    FINE_AMOUNT NUMBER(38,0),
    PENALTY_AMOUNT NUMBER(38,0),
    INTEREST_AMOUNT NUMBER(38,0),
    REDUCTION_AMOUNT NUMBER(38,0),
    PAYMENT_AMOUNT NUMBER(38,0),
    AMOUNT_DUE NUMBER(38,0)
);

INSERT INTO Fines(SUMMONS_NUMBER,PLATE,FINE_AMOUNT,PENALTY_AMOUNT,INTEREST_AMOUNT,REDUCTION_AMOUNT,PAYMENT_AMOUNT,AMOUNT_DUE) 
SELECT
    SUMMONS_NUMBER,
    PLATE, 
    TO_CHAR(FINE_AMOUNT,'$999,999,999.99')"FINE_AMOUNT",
    TO_CHAR(PENALTY_AMOUNT,'$999,999,999.99')"PENALTY_AMOUNT",
    TO_CHAR(INTEREST_AMOUNT,'$999,999,999.99')"INTEREST_AMOUNT",
    TO_CHAR(REDUCTION_AMOUNT,'$999,999,999.99')"REDUCTION_AMOUNT",
    TO_CHAR(PAYMENT_AMOUNT,'$999,999,999.99')"PAYMENT_AMOUNT",
    TO_CHAR(AMOUNT_DUE,'$999,999,999.99')"AMOUNT_DUE"
FROM
    VIOLATIONS
    
SELECT*
FROM Fines

ALTER TABLE FINES
ADD PRIMARY KEY (SUMMONS_NUMBER);

DROP TABLE FINES
--TABLE 6 --TABLE 6 --TABLE 6 --TABLE 6 --TABLE 6 --TABLE 6 --TABLE 6 --TABLE 6
--TABLE 6 --TABLE 6 --TABLE 6 --TABLE 6 --TABLE 6 --TABLE 6 --TABLE 6 --TABLE 6

--DELETE DUPLICATES
CREATE TABLE Precinct(
    PRECINCT NUMBER(38,0),
    COUNTY VARCHAR2(26 BYTE)
);
INSERT INTO Precinct(PRECINCT,COUNTY) 
SELECT
DISTINCT
    PRECINCT,
    COUNTY
FROM VIOLATIONS

ALTER TABLE PRECINCT
ADD PRIMARY KEY (PRECINCT);

SELECT*
FROM Precinct

DROP TABLE Precinct


--END --END --END --END --END --END --END --END --END --END --END --END --END 

--SCRAP --SCRAP --SCRAP --SCRAP --SCRAP --SCRAP --SCRAP --SCRAP --SCRAP --SCRAP
SELECT*
FROM VIOLATIONS
ORDER BY FINE_AMOUNT DESC;

SELECT VIOLATION, COUNT(1)
FROM VIOLATIONS
GROUP BY VIOLATION
ORDER BY 2 DESC;

SELECT STATE, COUNT(1), AVG(PAYMENT_AMOUNT),SUM(PAYMENT_AMOUNT)
FROM VIOLATIONS
GROUP BY STATE
ORDER BY 2 DESC

SELECT plate "License Plate", count(1)"Number Of Violations"
FROM VIOLATIONS
GROUP BY PLATE
ORDER BY 2 DESC
--SCRAP --SCRAP --SCRAP --SCRAP --SCRAP --SCRAP --SCRAP --SCRAP --SCRAP --SCRAP

--Project 2 DATABASE 331 --Project 2 DATABASE 331 --Project 2 DATABASE 331
--Project 2 DATABASE 331 --Project 2 DATABASE 331 --Project 2 DATABASE 331
--Project 2 DATABASE 331 --Project 2 DATABASE 331 --Project 2 DATABASE 331

--QUESTIONS --QUESTIONS --QUESTIONS --QUESTIONS --QUESTIONS --QUESTIONS
--Question 1

SELECT ISSUE_DATE, COUNT(1)"Number Of Violations"
FROM VIOLATIONS
WHERE   ISSUE_DATE >= '01-JAN-21' 
AND     ISSUE_DATE <= '01-JUN-21'
GROUP BY MONTH(VIOLATIONS)

SELECT TO_CHAR(ISSUE_DATE,"MM-DD-YYYY"),COUNT(1)"Number Of Violations"
FROM VIOLATIONS
GROUP BY TO_CHAR(ISSUE_DATE,"MM-DD-YYYY")
ORDER BY 1

SELECT EXTRACT(MONTH FROM ISSUE_DATE), COUNT(1)"Number Of Violations"
FROM VIOLATIONS
GROUP BY EXTRACT(MONTH FROM ISSUE_DATE)

--ANSWER--ANSWER--ANSWER--ANSWER--ANSWER--ANSWER
SELECT
  --EXTRACT(YEAR FROM ISSUE_DATE) AS year,
  EXTRACT(MONTH FROM  ISSUE_DATE) AS month,
  COUNT(1) AS count
FROM VIOLATIONS
GROUP BY
  --EXTRACT(YEAR FROM ISSUE_DATE),
  EXTRACT(MONTH FROM ISSUE_DATE)
  ORDER BY 1 ASC
  FETCH FIRST 6 ROWS ONLY

--ANSWER--ANSWER--ANSWER--ANSWER--ANSWER--ANSWER
SELECT (MAX(ISSUE_DATE))"TIME",COUNT(1)"Number Of Violations"
FROM VIOLATIONS
WHERE ISSUE_DATE >= add_months(MAX(ISSUE_DATE),-6)
GROUP BY ISSUE_DATE


SELECT ISSUE_DATE,COUNT(1)"Number Of Violations"
FROM VIOLATIONS
WHERE   ISSUE_DATE >= '01-JAN-21' 
AND     ISSUE_DATE <= '01-MAR-21'
GROUP BY DATE
ORDER BY 2 DESC;

CREATE TABLE Q1(IssueDate,Violation)
INSERT INTO
SELECT count(violation)
From VIOLATIONS;

SELECT plate "License Plate",count(1)"Number Of Violations"
FROM VIOLATIONS
GROUP BY PLATE
ORDER BY 2 DESC;

--Question 2
CREATE TABLE violationsByCounty(
    County VARCHAR2(26 BYTE),
    Number_Of_Violations NUMBER(38,0),
    Total_Fine_Amount NUMBER(38,2)
);
INSERT INTO violationsByCounty
SELECT COUNTY, COUNT(VIOLATION)"Number Of Violations",TO_CHAR(SUM(FINE_AMOUNT),'$999,999,999.99')"Total Fine Amount"
    FROM SMALLVIOLATIONS
    GROUP BY COUNTY
    ORDER BY 2 DESC

--Turn to Currency

SELECT*
FROM violationsByCounty

COMMIT 

DROP TABLE violationsByCounty
 
--Question 3
--CREATE TABLE violationsByPlate(License_Plate,License_State,Number_Of_Violations,Total_Cost)
--Missing State
SELECT PLATE "License Plate","STATE",TO_CHAR(COUNT(1),'999,999,999')"Number Of Violations",
    TO_CHAR(SUM(FINE_AMOUNT),'$999,999,999')"Total Fine Amount"
        FROM VIOLATIONS
        GROUP BY PLATE, "STATE"
        ORDER BY 4 DESC

SELECT "STATE"
FROM VIOLATIONS

--Question 4
--CREATE TABLE violationsByLicenseType(License_Type,Number_Of_Violations,Total_Fine_Amount)
SELECT LICENSE_TYPE, TO_CHAR(COUNT(1),'999,999,999')"Number Of Violations", 
    TO_CHAR(SUM(FINE_AMOUNT),'$999,999,999')"Total Fine Amount"
        FROM VIOLATIONS
        GROUP BY LICENSE_TYPE
        ORDER BY 2 DESC

--Question 5
--CREATE TABLE violationsByLicenseState(License_State,Number_Of_Violations,Total_Fine_Amount)
SELECT STATE,TO_CHAR(COUNT(1),'999,999,999')"Number Of Violations", 
    TO_CHAR(SUM(FINE_AMOUNT),'$999,999,999')"Total Fine Amount"
        FROM VIOLATIONS
        GROUP BY STATE
        ORDER BY 2 DESC

--Question 6
--CREATE TABLE doubleParkingViolations(Month_Of_Violation,Number_Of_Violations)
--Monthly
SELECT VIOLATION,ISSUE_DATE
    FROM VIOLATIONS
    WHERE VIOLATION like '%FIRE HYDRANT'
    AND ISSUE_DATE like '%JAN%'

--Question 7
--CREATE TABLE lastSixMonths(Violation,Number_Of_Violations,Total_Cost)
SELECT VIOLATION, TO_CHAR(COUNT(1),'999,999,999')"Number Of Violations", TO_CHAR(SUM(FINE_AMOUNT),'$999,999,999')"Total Fine Amount"
    FROM VIOLATIONS
    GROUP BY VIOLATION
    ORDER BY 2 DESC

--Question 8
--CREATE TABLE totalFines(Total_Fines)
SELECT VIOLATION,TO_CHAR(SUM(FINE_AMOUNT),'$999,999,999')"Total Fine Amount"
    FROM VIOLATIONS
    WHERE VIOLATION like '%DOUBLE PARKING%'
    GROUP BY VIOLATION

--Question 9
SELECT VIOLATION, TO_CHAR(COUNT(1),'999,999,999')"Number Of Violations"
    FROM VIOLATIONS
    WHERE VIOLATION like '%NO PARKING%'
    AND ISSUE_DATE like '%OCT%'
    GROUP BY VIOLATION
    ORDER BY 2 DESC
    
SELECT
  --EXTRACT(YEAR FROM ISSUE_DATE) AS year,
  EXTRACT(MONTH FROM  ISSUE_DATE) AS month,
  COUNT(1) AS count
FROM VIOLATIONS
GROUP BY
  --EXTRACT(YEAR FROM ISSUE_DATE),
  EXTRACT(MONTH FROM ISSUE_DATE)
  ORDER BY 1 ASC
  FETCH FIRST 12 ROWS ONLY


--Question 10
DESCRIBE SUMMONED_VEHICLE_OWNER
DESCRIBE SUMMONS
DESCRIBE FINES
DESCRIBE PRECINCT
DESCRIBE VEHICLE_INFO

--Question 11
SELECT * FROM v$version;



